force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Money put on this bet</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Player__c.TotalMoneyWon__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Values - Pending, Won, Lost</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bet__c/fields/WinRate__c.field-meta.xml
<CustomField>
    <fullName>WinRate__c</fullName>
    <description>Percent indicating how much money Player wins (9 means *1.09)</description>
    <label>Win Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/IsBlackList__c.field-meta.xml
<CustomField>
    <fullName>IsBlackList__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if the User is in the blacklist. No bets are allowed if true.</description>
    <label>Is Black List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(IsBlackList__c = true,	
			IMAGE(&quot;https://practice131-dev-ed--c.vf.force.com/resource/1664460403000/bandit?&quot;, &quot;bandit&quot;, 25,25),
			IF(TotalMoneyWon__c &lt; 0, 
						IMAGE(&quot;https://practice131-dev-ed--c.vf.force.com/resource/1664460686000/warning?&quot;, &quot;warning&quot;, 25,25),
						IF(TotalMoneyWon__c &gt;= 0 &amp;&amp; TotalMoneyWon__c &lt; 1000,
									null,
									IF(TotalMoneyWon__c &gt;= 1000 &amp;&amp; TotalMoneyWon__c &lt; 10000 ,
												IMAGE(&quot;https://practice131-dev-ed--c.vf.force.com/resource/1664457974000/Star?&quot;, &quot;star&quot;, 25,25),  
									   IMAGE(&quot;https://practice131-dev-ed--c.vf.force.com/resource/1664458313000/diamond?&quot;, &quot;diamond&quot;, 25,25)
												)
			     )
						)
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/TotalMoneyWon__c.field-meta.xml
<CustomField>
    <fullName>TotalMoneyWon__c</fullName>
    <description>All the money player won for all the times.</description>
    <label>Total Money Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TotalizatorDao.cls
public with sharing class TotalizatorDao {
    public static List<Player__c> getPlayers(Integer limitNumber, Integer offset) {
        List<Player__c> notBlockedPlayers = [SELECT Name 
                                             FROM Player__c 
                                             WHERE IsBlackList__c = false 
                                             LIMIT :limitNumber OFFSET :offset];
        return notBlockedPlayers;
    }

    public static List<AggregateResult> getGamesCount() {
        List<AggregateResult> countOfAllGames = [SELECT COUNT(Name) total FROM Game__c];
        return countOfAllGames;
    }

    public static Map<Id, decimal> getTotalMoneyWon(Set<Id> playerIds) {
        List<AggregateResult> sumOfAllWonBets = [SELECT Player__c playerId, SUM(Amount__c) total
                                                 FROM Bet__c
                                                 WHERE Status__c = 'Won' AND Player__c IN :playerIds
                                                 GROUP BY Player__c];
        
        Map<ID, decimal> playersMapWithMoneyWon = new Map<ID, decimal>();
        for(AggregateResult wons : sumOfAllWonBets) {
            playersMapWithMoneyWon.put((Id) wons.get('playerId'), (decimal) wons.get('total'));
        }
        return playersMapWithMoneyWon;
    }

    public static List<Player__c> getTopPlayers(Integer limitNumber, Integer offset) {
        List<Player__c> topPlayers = [SELECT Name, TotalMoneyWon__c 
                                             FROM Player__c
                                             ORDER BY TotalMoneyWon__c desc
                                             LIMIT :limitNumber OFFSET :offset];
        return topPlayers;
    }

    public static Map<Id, Integer> getMostPopularGames() {
    	Map<Id, Integer> gameBetsCountMap = new Map<Id, Integer>();
		for (AggregateResult aggRes : [
      		SELECT count(ID) betsCount, Game__c gameId
      		FROM Bet__c
      		GROUP BY Game__c
		]) {
    	    Id gameId = (Id) aggRes.get('gameId');
    	    Integer betsCount = (Integer) aggRes.get('betsCount');
    	    gameBetsCountMap.put(gameId, betsCount);
		}
        return gameBetsCountMap;
    }

    public static void createPlayer(String playerName, String playerEmail) {
        List<Player__c> playerToInsert = new List<Player__c>();
    	playerToInsert.add(new Player__c(Name__c = playerName, Email__c = playerEmail));
        Database.SaveResult[] srList = Database.insert(playerToInsert, false);
        for (Database.SaveResult sr : srList) {
    		if (sr.isSuccess()) {
        		System.debug('Successfully inserted Player. Player ID: ' + sr.getId());
    		} else {              
        		for(Database.Error err : sr.getErrors()) {                   
            		System.debug(err.getStatusCode() + ': ' + err.getMessage());
            		System.debug('Player fields that affected this error: ' + err.getFields());
        		}
            }
		}
    }
    
    public static void updateBet(Id betId, Decimal amount, Decimal percent) {
        Bet__c betToUpdate = [SELECT Id, Amount__c, WinRate__c 
                              FROM Bet__c 
         				      WHERE Id = :betId AND Amount__c != null AND WinRate__c != null];
        betToUpdate.Amount__c = amount;
        betToUpdate.WinRate__c = percent;
        Database.SaveResult sr = Database.update(betToUpdate, false);  
        if (!sr.isSuccess()) {              
        	for(Database.Error err : sr.getErrors()) {                   
            	System.debug(err.getStatusCode() + ': ' + err.getMessage());
            	System.debug('Fields that affected this error: ' + err.getFields());
        	}
    	} else System.debug('Successfully updated Bet');
    }
    
    public static void deleteBets(List<Id> betIds) {
        List<Bet__c> betsToDelete = [SELECT Id FROM Bet__c WHERE Id IN :betIds];
        if(betsToDelete.size() > 0) {
        	List<Database.DeleteResult> results = Database.delete(betsToDelete, false);
        	for (Database.DeleteResult dr : results) {
    			if (dr.isSuccess()) {
        			System.debug('Successfully deleted Bet. Bet ID: ' + dr.getId());
    			} else {              
        			for(Database.Error err : dr.getErrors()) {                   
            			System.debug(err.getStatusCode() + ': ' + err.getMessage());
            			System.debug('Bet Id that affected this error: ' + dr.getId());
        			}
            	}
			}
        } else System.debug('Bets not found for delete');
    }
    
    public static void createBet(Id gameId, Id playerId, Decimal amount, Decimal winRate) {
        List<Bet__c> betsToInsert = new List<Bet__c>();
    	betsToInsert.add(new Bet__c(Game__c = gameId, Player__c = playerId, Amount__c = amount, WinRate__c = winRate, Status__c = 'Pending'));
        Database.SaveResult[] srList = Database.insert(betsToInsert, false);
        for (Database.SaveResult sr : srList) {
    		if (sr.isSuccess()) {
        		System.debug('Successfully inserted Bet. Bet ID: ' + sr.getId());
    		} else {              
        		for(Database.Error err : sr.getErrors()) {                   
            		System.debug(err.getStatusCode() + ': ' + err.getMessage());
            		System.debug('Bet fields that affected this error: ' + err.getFields());
        		}
            }
		}
    }
}